An amusing attempt to run this project again after rediscovering it 4 years and 9 months later.
I forgot that I made this back in 2016 and I was curious to see if it would
still run after 4 years of bit rot. Because Clojure projects are good about
still running without modifications years later, right?

Wrong.

The first issue I ran into was:

java.lang.IllegalStateException: template already refers to: #'boot.core/template in namespace: adzerk.boot-reload
     clojure.lang.ExceptionInfo: template already refers to: #'boot.core/template in namespace: adzerk.boot-reload

Probably due to an incompatibility with my newer version of Boot.

So, I tried upgrading boot-reload to the latest version. Next error:

clojure.lang.ExceptionInfo: Call to clojure.core/ns did not conform to spec.
...
clojure.lang.Compiler$CompilerException: Syntax error macroexpanding clojure.core/ns at (cljs/source_map/base64_vlq.clj:1:1).

At this point, I just started upgrading all the deps in the hopes that using the
latest versions of everything would get it running.

I think that _almost_ worked, except that the Domina library seems to have
completely bit-rotted.

Checking in what I've got here in case I want to finish bringing this project up
to date, because I still think it's kinda funny.

Current status is that the backend runs, and the frontend builds if I take out
Domina. The next step is to replace Domina with something else that still works
with present-day ClojureScript.